### ISSUE TITLE
feat: Location tracking and Live Sharing

### ISSUE THREAD

**Issue by KreativeThinker** [KreativeThinker/lifefence-backend#3]
- [ ] Location classification (Tagging and naming by user)
- [ ] Location websocket connection
- [ ] Admin/parent tracking
- [x] Adding new location
- [ ] Preventing overlapping locations
