### ISSUE TITLE
feat: Budgeting and Expense tracking

### ISSUE THREAD

**Issue by KreativeThinker** [KreativeThinker/lifefence-backend#4]
- [ ] Allow for keeping track of expenses
- [ ] Budget day/month/trip/year
- [ ] Analyze location based spending habits
